MONIT-16650 - update Jaeger SDK
wavefrontHQ/distributed-tracing-sample-apps pull request #77
Opened 2020-11-24 22:29 UTC by thepeterstone

Update the Jaeger/OpenTracing SDK to v1.5.0 and update the instructions in the Readme.

2020-12-01 20:34 UTC, hanwavefront requested changes
A couple minor comments, otherwise LGTM, thanks!

2020-12-01 20:34 UTC, hanwavefront commented on distributed-tracing/dropwizard-app/README.md
> +4. Go to `dropwizard-app/common/src/main/java/com/wfsample/common/Tracing.java` and change the `Tracer init(String service)` method to return a [WavefrontTracer](https://github.com/wavefrontHQ/wavefr
Replace `io.opentracing.Tracer` with `JaegerTracer`

2020-12-01 20:34 UTC, hanwavefront commented on distributed-tracing/dropwizard-app/common/src/main/java/com/wfsample/common/Tracing.java
> +  public static io.opentracing.Tracer init(String service) {
`Tracer` doesn't need to be fully qualified name here

2020-12-01 20:34 UTC, hanwavefront commented on distributed-tracing/dropwizard-app/pom.xml
> +        </dependency>
Is okhttp still needed?

2020-12-04 08:11 UTC, hanwavefront approved these changes
LGTM

2020-12-07 19:13 UTC, sushantdewan123 approved these changes

2020-12-07 19:14 UTC, merged